{% set name = "robin_hood" %}
{% set version = "3.11.5" %}
{% set organization = "martinus" %}
{% set repository = "robin-hood-hashing" %}
{% set sha256 = "3693e44dda569e9a8b87ce8263f7477b23af448a3c3600c8ab9004fe79c20ad0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ organization }}/{{ repository }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -e ${PREFIX}/include/robin_hood.h  # [not win]
    - test -e ${PREFIX}/lib/cmake/robin_hood/robin_hoodConfig.cmake  # [not win]
    - test -e ${PREFIX}/lib/cmake/robin_hood/robin_hood-targets.cmake  # [not win]

    - if not exist %LIBRARY_PREFIX%\include\robin_hood.h (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\robin_hood\robin_hoodConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\robin_hood\robin_hood-targets.cmake (exit 1)  # [win]

about:
  home: https://github.com/{{ organization }}/{{ repository }}/
  summary: 'Fast & memory efficient hashtable based on robin hood hashing for C++11/14/17/20'
  description: |
    `robin_hood::unordered_map` and `robin_hood::unordered_set` is a platform independent
    replacement for `std::unordered_map` / `std::unordered_set` which is both faster and
    more memory efficient for real-world use cases.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/{{ organization }}/{{ repository }}/

extra:
  recipe-maintainers:
    - jjerphan
    - DerThorsten
    - JohanMabille
